your-links/src/App.js
your-links/src/index.js

last changes for tonight- finish routing tomorrow

adding routing

---

README.md

just got the domain for this project- start by creating a simple react-app with a login attached then you need to figure out a way to generate a pretty looking webpage and then post it to IPFS

yourlinks.io

---

development/open_links_development.md

This is the second dev doc for this project

create dev doc 1

---

README.md
ol_react/README.md
ol_react/src/App.js
ol_react/src/Home.js
ol_react/src/index.js

Adding Auth0 Objects

---

.gitignore
after/.env
after/README.md

Still need to fix callback URL

Fixes with login

---

openlinks/package.json
openlinks/src/render.tsx
openlinks/src/tsconfig.json

Added HTML Generator

---

openlinks/src/Private.js
openlinks/src/index.css

Start on getting the generator working

Updates from last night

---

reactapp/server.js

last update for the night-morning-almost afternoon.... ugh

everything seems good

---

reactapp/src/Auth/Auth.js

You live as long as the last person who remembers you

Documentation additions

---

README.md
development/open_links_development.md

These milestones will make be the bulk of this project, after this all that is next is getting it onto a server for hosting

Added Milestones 

---

reactapp/package-lock.json
reactapp/server.js

weekend changes

---

README.md
development/open_links_development.md

First Rest-API's are finished. Moving on to UI in react

Rest API's Finished

---

development/sample.html

cleaning up comments

---

README.md

Added gateway link- i am always looking for this

for future reference

---

README.md

This is what I am working on right now... API finished last night, now its time for the frontend

current push documentation

---

client/src/App.js

deleted empty line

---

README.md
development/devDoc.md

you updated your servers, now update this

Submit and add new code

---

README.md
development/upload_function.js

updated ui

---

README.md
development/devDoc.md
package-lock.json

readme updates

---

README.md

Add new files from this weeks code sprint!

future project updates

---

README.md

I think this is outdated- update with new screenshots

fixed readme-

---

README.md

Work on adding the function to a repo maybe too

more updates added to md

---

README.md

Add this privacy policy to the new updated homepage

readme updates + privacy policy

---

README.md

Last image had pop-up. This is a correction to the last image I sent here... Check better before uploading...

Image Correction

---

development/devDoc.md

Auth0 Configuration Instructions

---

README.md

simple npm install and npm start commands added to readme

npm install instructions

---

README.md

Update Google Authentication problem. Issue #106 Auth0 Dev Key problem. 
- Submit the info you need to for authentication based on Google account.

current sprint info/documentation

---

README.md

There was a link that didn't make sense or work so this is a fix to that

Correct Dev Document

---

README.md

Thanks so much Yasir (idk why I cannot tag him, fix this asap)
- Add required sdk modules to our lambda layer config
- Add s3 service to our openlinks_utility Lambda layer
- Added the new /themes/config lambda configuration with S3 integration API Gateway

Sprint 8 Completed

---

README.md

A few edits I missed in the last PR.

A few minor edits

---

README.md

- Homepage re-factoring(new images, styles, text)
- Finish writing Auth0 Authentication Setup instructions(Partially Completed)
- Web3.name(IPNS) integration documentation
- IPNS Integration(@Yasir TYSM!)
- Auth0 Development Setup Instructions
- Homepage Updates(Finalize changes)
- Change IPFS Gateway configuration from dweb.link back to nft.storage

dec sprint notes

---

README.md

Thank you Web3.Storage for the awesome interview about our project Openlinks!

case study added to readme

---

README.md

updated the readme with the updates for this next sprint

Readme Sprint Updates
